version: '3.8'
services:
  mongodb:
    container_name: mongodb_2
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    command: npm run start:dev
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
